# Working With Numpy Library (Arrays)

In this project, the `numpy` module is already installed. If you need, you can run:
```bash
pip install numpy
```
For more information, check the [NumPy installation page](https://numpy.org/install/).

---

In [1]:
import numpy as np

### 1. Creating a NumPy Array
A numpy array is a a way to represent a Linear Algebra Vector. It resembles a Python List, but it can only store a single type of value.

To create an array:

In [2]:
arr = np.array([1, 2, 3, 4, 5])

(arr)

array([1, 2, 3, 4, 5])

### 2. Array of Zeros or Ones

You can create an array (or even a Matrix (an array of arrays)) filled with zeroes or ones:

In [3]:
zeroes_arr = np.zeros(3)

(zeroes_arr)

array([0., 0., 0.])

In [4]:
zeroes_mtx = np.zeros((3, 3)) # a 3x3 matrix of zeros

(zeroes_mtx)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# you can do the same with ones

ones_arr = np.ones(2)
ones_mtx = np.ones((2, 4))

(ones_arr, ones_mtx)

(array([1., 1.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

### 3. Creating a Range of Numbers
To create a sequence of numbers:

In [6]:
range_arr = np.arange(10, 50, 5) # from 10 to 50, step by 5

(range_arr)

array([10, 15, 20, 25, 30, 35, 40, 45])

### 4. Creating a Linearly Spaced Array
To create a series of values, evenly spaced between two bounds:

In [7]:
linear_spaced = np.linspace(0, 1, 5) # 5 values from 0 to 1

(linear_spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 5. Reshaping an Array
To transmute the shape of an array, altering its dimensions:

In [11]:
original = np.arange(9)

(original)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
reshaped = original.reshape((3, 3))

(reshaped)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6. Basic Array Operations
To perform elemental vector manipulations upon the arrays:

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

(a, b)

(array([1, 2, 3]), array([4, 5, 6]))

In [17]:
sum_arr = a + b # element-wise addition
(sum_arr)

array([5, 7, 9])

In [18]:
diff_arr = b - a # element-wise subtraction

(diff_arr)

array([3, 3, 3])

In [19]:
product_arr = a * b # element-wise multiplication

(product_arr)

array([ 4, 10, 18])

### 7. Matrix Multiplication
Basic dot product Operation:

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

(a, b)

(array([1, 2, 3]), array([4, 5, 6]))

In [21]:
result = np.dot(a.reshape(1, 3), b.reshape(3, 1)) # Dot product of a and b

(result)

array([[32]])

### 8. Accessing Array Elements
Accessing array elements shares the same syntax of Python Lists:

In [23]:
element = a[2] # retrieve the third element of array 'a'

print(f"Array A: {a}")
print(f"3rd Element: {element}")

Array A: [1 2 3]
3rd Element: 3


In [25]:
row_2 = reshaped[1, :] # Retrieve the second row of 'reshaped'

print(f"Reshaped:\n {reshaped}")
print(f"2nd row: {row_2}")

Reshaped:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
2nd row: [3 4 5]


### 9. Boolean Indexing
To filter the elements of an array through the sieve of conditionals:

In [26]:
filtered = a[a > 2] # Elements of 'a' greater than 2

(filtered)

array([3])

### 10. Aggregations and Statistics
Statistical operations on np arrays:

In [27]:
mean = np.mean(a)
maximum = np.max(a)
sum = np.sum(a)

(mean, maximum, sum)

(2.0, 3, 6)